select
    PRODUCT_CODE,
    sum(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) as SALES
from
    PRODUCT join OFFLINE_SALE
    on OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
group by
    PRODUCT_CODE
order by
    SALES desc,
    PRODUCT_CODE